### ISSUE TITLE
React Component for About Us page

### ISSUE THREAD

**Issue by 201801057** [201801057/Group-17-Faculty-Staff-Directory#10]
The component should be inline with the requirements mentioned.

**Comment by tulsishah309** [comment]
I want to do login, Delete entry, and Admin access in BackEnd.

**Comment by AkashParmar91** [comment]
I want to work on this issue

**Comment by 201801057** [comment]
Okay I am assigning it to you.

**Comment by 201801057** [comment]
#46 Done
