### ISSUE TITLE
Backend Implementation of Login

### ISSUE THREAD

**Issue by 201801057** [201801057/Group-17-Faculty-Staff-Directory#2]
The implementation should contain all the listed features developed in the django framework.

**Comment by tulsishah309** [comment]
I want to do login, Delete entry, and Admin access in BackEnd.

**Comment by 201801057** [comment]
Ok, I have assigned this issue to you.

**Comment by tulsishah309** [comment]
[forms.txt](https://github.com/201801057/Group-17-Faculty-Staff-Directory/files/6298678/forms.txt)
[login.txt](https://github.com/201801057/Group-17-Faculty-Staff-Directory/files/6298679/login.txt)
[views.txt](https://github.com/201801057/Group-17-Faculty-Staff-Directory/files/6298681/views.txt)


Login done




``
