### ISSUE TITLE
UI/UX Design of the Website 

### ISSUE THREAD

**Issue by 201801057** [201801057/Group-17-Faculty-Staff-Directory#3]
The design should have all the listed features keeping in mind the requirements.

**Comment by Urmik350** [comment]
https://www.figma.com/proto/qqlIxgBJwvIN7l5YwnEt4I/Untitled?node-id=183%3A0&viewport=-844%2C357%2C0.2070731669664383&scaling=scale-down&page-id=0%3A1

**Comment by 201801057** [comment]
Any updates about the prototype of our website ?
